import { ProductType } from "@/types";

export const productSeedData: Omit<ProductType, "uuid">[] = [
    {
        productId: "extra-virgin-olive-oil",
        name: "Extra Virgin Olive Oil",
        nameIt: "Olio Extravergine di Oliva",
        description: "Cold-pressed olive oil from our Tuscan groves, 500ml bottle.",
        descriptionIt: "Olio spremuto a freddo dai nostri oliveti, bottiglia da 500ml.",
        price: 12,
        unit: "bottle",
        unitIt: "bottiglia",
        inStock: true,
        seasonal: false,
    },
    {
        productId: "homemade-wine",
        name: "Homemade Wine",
        nameIt: "Vino della Casa",
        description: "Red wine from our vineyard in the Pearl Valley, 750ml.",
        descriptionIt: "Vino rosso del nostro vigneto nella Valle della Perla, 750ml.",
        price: 15,
        unit: "bottle",
        unitIt: "bottiglia",
        inStock: true,
        seasonal: true,
    },
    {
        productId: "seasonal-jam",
        name: "Seasonal Fruit Jam",
        nameIt: "Confettura di Frutta di Stagione",
        description: "Handmade jam from garden fruit, 280g jar.",
        descriptionIt: "Confettura artigianale dalla frutta dell'orto, vasetto da 280g.",
        price: 8,
        unit: "jar",
        unitIt: "vasetto",
        inStock: true,
        seasonal: true,
    },
    {
        productId: "organic-honey",
        name: "Organic Honey",
        nameIt: "Miele Biologico",
        description: "Raw honey from local beekeepers near Lake Bolsena, 250g.",
        descriptionIt: "Miele crudo da apicoltori locali vicino al Lago di Bolsena, 250g.",
        price: 10,
        unit: "jar",
        unitIt: "vasetto",
        inStock: true,
        seasonal: false,
    },
];
